// Copyright 2014 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Collections.Immutable;
using System.Linq;
using Starlark.Spelling;

namespace Starlark.Syntax;

/// <summary>
/// The Resolver resolves each identifier in a syntax tree to its binding, and performs other
/// validity checks.
///
/// <para>When a variable is defined, it is visible in the entire block. For example, a global
/// variable is visible in the entire file; a variable in a function is visible in the entire
/// function block (even on the lines before its first assignment).</para>
///
/// <para>Resolution is a mutation of the syntax tree, as it attaches binding information to
/// Identifier nodes. Resolution errors are reported in the analogous manner to scan/parse errors:
/// for a StarlarkFile, they are appended to <c>StarlarkFile.errors</c>; for an expression they are
/// reported by a SyntaxError.Exception exception.</para>
/// </summary>
public sealed class Resolver : NodeVisitor
{
    /// <summary>Scope discriminates the scope of a binding: global, local, etc.</summary>
    public enum Scope
    {
        /// <summary>Binding is local to a function, comprehension, or file (e.g. load).</summary>
        LOCAL,

        /// <summary>Binding is non-local and occurs outside any function or comprehension.</summary>
        GLOBAL,

        /// <summary>Binding is local to a function, comprehension, or file, but shared with nested functions.</summary>
        CELL,

        /// <summary>Binding is an implicit parameter whose value is the CELL of some enclosing function.</summary>
        FREE,

        /// <summary>Binding is predeclared by the application (e.g. glob in Bazel).</summary>
        PREDECLARED,

        /// <summary>Binding is predeclared by the core (e.g. None).</summary>
        UNIVERSAL,
    }

    /// <summary>Helper for the lowercase toString behavior of <see cref="Scope"/>.</summary>
    public static string ScopeToString(Scope scope)
    {
        return scope.ToString().ToLowerInvariant();
    }

    /// <summary>
    /// A Binding is a static abstraction of a variable. The Resolver maps each Identifier to a
    /// Binding.
    /// </summary>
    public class Binding
    {
        internal Scope scope;

        // index within frame (LOCAL/CELL), freevars (FREE), or module (GLOBAL)
        private readonly int index;

        // True if there is at least one binding occurrence in the resolved syntax tree; false for
        // bindings that are generated by successfully matching a name in Module#resolve.
        internal readonly bool isSyntactic;

        // If isSyntactic is true, the first binding occurrence of this symbol. Otherwise, the first
        // occurrence of this symbol (which must be non-binding).
        internal readonly Identifier first;

        // Set by TypeTagger (possibly more than once) if applicable. Null is treated as untyped/Any.
        private StarlarkType? type;

        internal Binding(Scope scope, int index, bool isSyntactic, Identifier first)
        {
            this.scope = scope;
            this.index = index;
            this.isSyntactic = isSyntactic;
            this.first = first;
        }

        /// <summary>
        /// Returns the first binding occurrence of this symbol, or if there is none, the first
        /// non-binding occurrence.
        /// </summary>
        internal Identifier GetFirst() => first;

        /// <summary>Returns whether any binding occurrence of this symbol appears in the syntax tree.</summary>
        internal bool IsSyntactic() => isSyntactic;

        /// <summary>Returns the name of this binding's identifier.</summary>
        public string GetName() => first.GetName();

        /// <summary>Returns the scope of the binding.</summary>
        public Scope GetScope() => scope;

        /// <summary>
        /// Returns the index of a binding within its function's frame (LOCAL/CELL), freevars (FREE),
        /// or module (GLOBAL).
        /// </summary>
        public int GetIndex() => index;

        public override string ToString()
        {
            string declaredAt =
                isSyntactic
                    ? first.GetStartLocation().ToString()!
                    : scope == Scope.UNIVERSAL || scope == Scope.PREDECLARED
                        ? "<builtin>"
                        // e.g., on a previous input of the REPL
                        : "<previously defined>";
            return string.Format(
                "{0}[{1}] {2} @ {3}", ScopeToString(scope), index, first.GetName(), declaredAt);
        }

        /// <summary>Returns the type of this binding, or null if a type is not set.</summary>
        public StarlarkType? GetType() => type;

        /// <summary>Assigns (or clears) a type to this binding. May be called more than once.</summary>
        internal void SetType(StarlarkType? type)
        {
            this.type = type;
        }
    }

    /// <summary>A <see cref="Binding"/> for a variable of a list or dict comprehension.</summary>
    public sealed class ComprehensionBinding : Binding
    {
        // Used only for determining the range of locations encompassing the comprehension's lexical
        // scope.
        private readonly Comprehension node;

        internal ComprehensionBinding(int index, Identifier first, Comprehension node)
            : base(Scope.LOCAL, index, /* isSyntactic= */ true, first)
        {
            this.node = node;
        }

        /// <summary>Returns true if the given location falls within the scope of the comprehension.</summary>
        public bool InScope(Location loc)
        {
            if (!loc.File.Equals(node.GetStartLocation().File))
            {
                return false;
            }
            // Following Python3, the first for clause of a comprehension is resolved outside the
            // comprehension block. All the other loops are resolved in the scope of their own
            // bindings, permitting forward references.
            var for0 = (Comprehension.For)node.GetClauses()[0];
            Expression iterable0 = for0.GetIterable();
            if (loc.CompareTo(iterable0.GetStartLocation()) >= 0
                && loc.CompareTo(iterable0.GetEndLocation()) < 0)
            {
                return false;
            }
            if (loc.CompareTo(node.GetStartLocation()) >= 0
                && loc.CompareTo(node.GetEndLocation()) < 0)
            {
                return true;
            }
            return false;
        }
    }

    /// <summary>A Resolver.Function records information about a resolved function.</summary>
    public sealed class Function
    {
        private readonly string name;
        private readonly Location location;
        private readonly ImmutableArray<Parameter> parameters;
        private readonly ImmutableArray<Statement> body;
        private readonly bool hasVarargs;
        private readonly bool hasKwargs;
        private readonly int numKeywordOnlyParams;
        private readonly ImmutableArray<string> parameterNames;
        private readonly bool isToplevel;
        private readonly ImmutableArray<Binding> locals;
        private readonly int[] cellIndices;
        private readonly ImmutableArray<Binding> freevars;
        private readonly ImmutableArray<string> globals;

        // Set by type checking (possibly more than once) if applicable. Null is treated as
        // untyped / Any. Always null for the function associated with a StarlarkFile object.
        private Types.CallableType? functionType;

        // Set by type checking if applicable.
        private bool usesTypeSyntax;

        internal Function(
            string name,
            Location loc,
            ImmutableArray<Parameter> parameters,
            ImmutableArray<Statement> body,
            bool hasVarargs,
            bool hasKwargs,
            int numKeywordOnlyParams,
            IReadOnlyList<Binding> locals,
            IReadOnlyList<Binding> freevars,
            IReadOnlyList<string> globals)
        {
            this.name = name;
            this.location = loc;
            this.parameters = parameters;
            this.body = body;
            this.hasVarargs = hasVarargs;
            this.hasKwargs = hasKwargs;
            this.numKeywordOnlyParams = numKeywordOnlyParams;

            var names = ImmutableArray.CreateBuilder<string>(parameters.Length);
            foreach (Parameter p in parameters)
            {
                names.Add(p.GetName()!);
            }
            this.parameterNames = names.ToImmutable();

            this.isToplevel = name.Equals("<toplevel>", StringComparison.Ordinal);
            this.locals = locals.ToImmutableArray();
            this.freevars = freevars.ToImmutableArray();
            this.globals = globals.ToImmutableArray();

            // Create an index of the locals that are cells.
            int ncells = 0;
            int nlocals = this.locals.Length;
            for (int i = 0; i < nlocals; i++)
            {
                if (this.locals[i].scope == Scope.CELL)
                {
                    ncells++;
                }
            }
            this.cellIndices = new int[ncells];
            for (int i = 0, j = 0; i < nlocals; i++)
            {
                if (this.locals[i].scope == Scope.CELL)
                {
                    cellIndices[j++] = i;
                }
            }
        }

        /// <summary>
        /// Returns the name of the function. It may be "&lt;toplevel&gt;" for the implicit function
        /// that holds the top-level statements of a file, or "&lt;expr&gt;" for the implicit
        /// function that evaluates a single expression.
        /// </summary>
        public string GetName() => name;

        /// <summary>Returns the value denoted by the function's doc string literal, or null if absent.</summary>
        public string? GetDocumentation()
        {
            if (GetBody().Count == 0)
            {
                return null;
            }
            Statement first = GetBody()[0];
            if (first is not ExpressionStatement exprStmt)
            {
                return null;
            }
            Expression expr = exprStmt.GetExpression();
            if (expr is not StringLiteral strLit)
            {
                return null;
            }
            return strLit.GetValue();
        }

        /// <summary>Returns the function's local bindings, parameters first.</summary>
        public IReadOnlyList<Binding> GetLocals() => locals;

        /// <summary>
        /// Returns the indices within <see cref="GetLocals"/> of the "cells", that is, local
        /// variables of this function that are shared with nested functions. The caller must not
        /// modify the result.
        /// </summary>
        public int[] GetCellIndices() => cellIndices;

        /// <summary>
        /// Returns the list of names of globals referenced by this function. The order matches the
        /// indices used in compiled code.
        /// </summary>
        public IReadOnlyList<string> GetGlobals() => globals;

        /// <summary>
        /// Returns the list of enclosing CELL or FREE bindings referenced by this function.
        /// </summary>
        public IReadOnlyList<Binding> GetFreeVars() => freevars;

        /// <summary>Returns the location of the function's identifier.</summary>
        public Location GetLocation() => location;

        /// <summary>
        /// Returns the function's parameters, in "run-time order": non-keyword-only parameters,
        /// keyword-only parameters, <c>*args</c>, and finally <c>**kwargs</c>. A bare <c>*</c>
        /// parameter is dropped.
        /// </summary>
        public IReadOnlyList<Parameter> GetParameters() => parameters;

        /// <summary>Returns the effective statements of the function's body.</summary>
        public IReadOnlyList<Statement> GetBody() => body;

        /// <summary>Reports whether the function has an <c>*args</c> parameter.</summary>
        public bool HasVarargs() => hasVarargs;

        /// <summary>Reports whether the function has a <c>**kwargs</c> parameter.</summary>
        public bool HasKwargs() => hasKwargs;

        /// <summary>Returns the number of the function's keyword-only parameters.</summary>
        public int NumKeywordOnlyParams() => numKeywordOnlyParams;

        /// <summary>Returns the number of non-residual parameters.</summary>
        public int GetNumNonResidualParameters()
        {
            return parameters.Length - (hasKwargs ? 1 : 0) - (hasVarargs ? 1 : 0);
        }

        /// <summary>Returns the number of ordinary (non-residual, non-keyword-only) parameters.</summary>
        public int GetNumOrdinaryParameters()
        {
            return parameters.Length
                - (hasKwargs ? 1 : 0)
                - (hasVarargs ? 1 : 0)
                - numKeywordOnlyParams;
        }

        /// <summary>Returns the names of the parameters. Order is as for <see cref="GetParameters"/>.</summary>
        public IReadOnlyList<string> GetParameterNames() => parameterNames;

        /// <summary>
        /// isToplevel indicates that this is the &lt;toplevel&gt; function containing top-level
        /// statements of a file.
        /// </summary>
        public bool IsToplevel() => isToplevel;

        /// <summary>Returns the type of this function, or null if a type is not set.</summary>
        public Types.CallableType? GetFunctionType() => functionType;

        /// <summary>Assigns (or clears) a type to this function. May be called more than once.</summary>
        internal void SetFunctionType(Types.CallableType? functionType)
        {
            this.functionType = functionType;
        }

        /// <summary>
        /// After type tagging has been performed, returns true if the non-lambda function is
        /// considered to use static typing syntax - in other words, type annotations or <c>cast</c>
        /// expressions.
        /// </summary>
        public bool UsesTypeSyntax() => usesTypeSyntax;

        /// <summary>Tags this function as using type syntax.</summary>
        internal void SetUsesTypeSyntax()
        {
            this.usesTypeSyntax = true;
        }
    }

    /// <summary>
    /// A static abstraction of a Starlark Module, that resolves names to scope and type information
    /// rather than to dynamic Starlark values.
    /// </summary>
    public interface IModule : TypeContext
    {
        /// <summary>
        /// Resolves a name to a GLOBAL, PREDECLARED, or UNIVERSAL binding.
        /// </summary>
        /// <exception cref="Undefined">if the name is not defined.</exception>
        Scope Resolve(string name);

        /// <summary>
        /// Resolves a name to a corresponding type constructor.
        /// </summary>
        /// <returns>null if the name is known but not a type constructor.</returns>
        /// <exception cref="Undefined">if the name is not defined, as per <see cref="Resolve"/>.</exception>
        TypeConstructor? GetTypeConstructor(string name);
    }

    /// <summary>
    /// An Undefined exception indicates a failure to resolve a top-level name. If <c>Candidates</c>
    /// is non-null, it provides the set of accessible top-level names, which, along with local
    /// names, will be used as candidates for spelling suggestions.
    /// </summary>
    public sealed class Undefined : Exception
    {
        public ISet<string>? Candidates { get; }

        public Undefined(string message, ISet<string>? candidates)
            : base(message)
        {
            this.Candidates = candidates;
        }

        public Undefined(string message)
            : this(message, /* candidates= */ null)
        {
        }
    }

    /// <summary>Represents a lexical block.</summary>
    private sealed class Block
    {
        internal readonly Block? parent; // enclosing block, or null for tail of list
        internal Node? syntax; // Comprehension, DefStatement/LambdaExpression, StarlarkFile, or null
        internal readonly List<Binding> frame; // accumulated locals of enclosing function

        // Accumulated CELL/FREE bindings of the enclosing function that will provide the values for
        // the free variables of this function; null for toplevel functions and expressions.
        internal readonly List<Binding>? freevars;

        // Bindings for names defined in this block. Also, as an optimization, memoized lookups of
        // enclosing bindings.
        internal readonly Dictionary<string, Binding> bindings = new();

        internal Block(Block? parent, Node? syntax, List<Binding> frame, List<Binding>? freevars)
        {
            this.parent = parent;
            this.syntax = syntax;
            this.frame = frame;
            this.freevars = freevars;
        }
    }

    private readonly List<SyntaxError> errors;
    private readonly FileOptions options;
    private readonly IModule module;

    // List whose order defines the numbering of global variables in this program.
    private readonly List<string> globals = new();

    // A map from global variable names to their doc comments; added to by bind(); null if doc
    // comments for global variables are not being collected.
    private readonly Dictionary<string, DocComments>? docCommentsMap;

    // A cache of PREDECLARED, UNIVERSAL, and GLOBAL bindings queried from the module.
    private readonly Dictionary<string, Binding> toplevel = new();

    // Linked list of blocks, innermost first, for functions and comprehensions and (finally) file.
    private Block locals = null!;
    private int loopCount;

    private Resolver(
        List<SyntaxError> errors,
        IModule module,
        FileOptions options,
        Dictionary<string, DocComments>? docCommentsMap)
    {
        // Don't visit keyword args or dot expression fields -- those aren't symbols.
        this.skipNonSymbolIdentifiers = true;

        this.errors = errors;
        this.module = module;
        this.options = options;
        this.docCommentsMap = docCommentsMap;
    }

    // Formats and reports an error at the start of the specified node.
    private void Errorf(Node node, string format, params object?[] args)
    {
        Errorf(node.GetStartLocation(), format, args);
    }

    // Formats and reports an error at the specified location.
    private void Errorf(Location loc, string format, params object?[] args)
    {
        errors.Add(new SyntaxError(loc, string.Format(format, args)));
    }

    /// <summary>
    /// First pass: add bindings for all variables to the current block. This is done because symbols
    /// are sometimes used before their definition point.
    /// </summary>
    private void CreateBindingsForBlock(IEnumerable<Statement> stmts)
    {
        foreach (Statement stmt in stmts)
        {
            CreateBindings(stmt);
        }
    }

    private void CreateBindings(Statement stmt)
    {
        switch (stmt.Kind)
        {
            case Statement.StatementKind.ASSIGNMENT:
                {
                    var assignStmt = (AssignmentStatement)stmt;
                    CreateBindingsForLHS(assignStmt.GetLHS(), assignStmt.GetDocComments());
                    break;
                }

            case Statement.StatementKind.VAR:
                {
                    var varStmt = (VarStatement)stmt;
                    Bind(varStmt.GetIdentifier(), /* isLoad= */ false, varStmt.GetDocComments());
                    break;
                }

            case Statement.StatementKind.IF:
                {
                    var ifStmt = (IfStatement)stmt;
                    CreateBindingsForBlock(ifStmt.GetThenBlock());
                    if (ifStmt.GetElseBlock() != null)
                    {
                        CreateBindingsForBlock(ifStmt.GetElseBlock()!);
                    }
                    break;
                }

            case Statement.StatementKind.FOR:
                {
                    var forStmt = (ForStatement)stmt;
                    CreateBindingsForLHS(forStmt.GetVars(), /* docComments= */ null);
                    CreateBindingsForBlock(forStmt.GetBody());
                    break;
                }

            case Statement.StatementKind.DEF:
                {
                    var defStmt = (DefStatement)stmt;
                    Bind(defStmt.GetIdentifier(), /* isLoad= */ false, /* docComments= */ null);
                    break;
                }

            case Statement.StatementKind.LOAD:
                {
                    var load = (LoadStatement)stmt;
                    var names = new HashSet<string>();
                    foreach (LoadStatement.Binding b in load.GetBindings())
                    {
                        // Reject load('...', '_private').
                        Identifier orig = b.GetOriginalName();
                        if (orig.IsPrivate() && !options.AllowLoadPrivateSymbols)
                        {
                            Errorf(orig, "symbol '{0}' is private and cannot be imported", orig.GetName());
                        }

                        // A load statement may not bind a single name more than once, even if
                        // options.allowToplevelRebinding.
                        Identifier local = b.GetLocalName();
                        if (names.Add(local.GetName()))
                        {
                            Bind(local, /* isLoad= */ true, /* docComments= */ null);
                        }
                        else
                        {
                            Errorf(local, "load statement defines '{0}' more than once", local.GetName());
                        }
                    }
                    break;
                }

            case Statement.StatementKind.TYPE_ALIAS:
                {
                    if (options.ResolveTypeSyntax)
                    {
                        var typeStmt = (TypeAliasStatement)stmt;
                        Bind(typeStmt.GetIdentifier(), /* isLoad= */ false, /* docComments= */ null);
                    }
                    break;
                }

            // nothing to declare
            case Statement.StatementKind.EXPRESSION:
            case Statement.StatementKind.FLOW:
            case Statement.StatementKind.RETURN:
                break;
        }
    }

    /// <summary>Calls <see cref="Bind"/> for appropriate identifiers of the LHS of an assignment.</summary>
    private void CreateBindingsForLHS(Expression lhs, DocComments? docComments)
    {
        foreach (Identifier id in Identifier.BoundIdentifiers(lhs))
        {
            Bind(id, /* isLoad= */ false, docComments);
        }
    }

    /// <summary>
    /// Extends the visit() traversal to the lhs of an assignment or for loop.
    /// </summary>
    private void Assign(Expression lhs)
    {
        if (lhs is Identifier id)
        {
            // Bindings are created by the first pass (createBindings).
            AssertIsBound(id);
        }
        else if (lhs is IndexExpression)
        {
            Visit(lhs);
        }
        else if (lhs is ListExpression listExpr)
        {
            foreach (Expression elem in listExpr.GetElements())
            {
                Assign(elem);
            }
        }
        else if (lhs is DotExpression dotExpr)
        {
            Visit(dotExpr.GetObject());
            // Do not visit the field. It is an identifier but does not correspond to a binding.
        }
        else
        {
            Errorf(lhs, "cannot assign to '{0}'", lhs);
        }
    }

    private void AssertIsBound(Identifier id)
    {
        if (id.GetBinding() == null)
        {
            throw new InvalidOperationException(
                string.Format("{0} expected to be bound", id.GetName()));
        }
    }

    private void AssertIsNotBound(Identifier id)
    {
        if (id.GetBinding() != null)
        {
            throw new InvalidOperationException(
                string.Format("{0} expected to not be bound", id.GetBinding()));
        }
    }

    public override void Visit(Identifier id)
    {
        // The visit() traversal should not reach any Identifier node more than once. It also should
        // not reach any binding occurrence of an Identifier at all -- those are set by the 1st pass.
        AssertIsNotBound(id);
        Binding? bind = Use(id);
        if (bind != null)
        {
            id.SetBinding(bind);
            return;
        }
    }

    public override void Visit(ReturnStatement node)
    {
        if (locals.syntax is StarlarkFile)
        {
            Errorf(node, "return statements must be inside a function");
        }
        base.Visit(node);
    }

    public override void Visit(CallExpression node)
    {
        // validate call arguments
        bool seenVarargs = false;
        bool seenKwargs = false;
        HashSet<string>? keywords = null;
        foreach (Argument arg in node.GetArguments())
        {
            if (arg is Argument.Positional)
            {
                if (seenVarargs)
                {
                    Errorf(arg, "positional argument may not follow *args");
                }
                else if (seenKwargs)
                {
                    Errorf(arg, "positional argument may not follow **kwargs");
                }
                else if (keywords != null)
                {
                    Errorf(arg, "positional argument may not follow keyword argument");
                }
            }
            else if (arg is Argument.Keyword)
            {
                string keyword = arg.GetName()!;
                if (seenVarargs)
                {
                    Errorf(arg, "keyword argument {0} may not follow *args", keyword);
                }
                else if (seenKwargs)
                {
                    Errorf(arg, "keyword argument {0} may not follow **kwargs", keyword);
                }
                keywords ??= new HashSet<string>();
                if (!keywords.Add(keyword))
                {
                    Errorf(arg, "duplicate keyword argument: {0}", keyword);
                }
            }
            else if (arg is Argument.Star)
            {
                if (seenKwargs)
                {
                    Errorf(arg, "*args may not follow **kwargs");
                }
                else if (seenVarargs)
                {
                    Errorf(arg, "multiple *args not allowed");
                }
                seenVarargs = true;
            }
            else if (arg is Argument.StarStar)
            {
                if (seenKwargs)
                {
                    Errorf(arg, "multiple **kwargs not allowed");
                }
                seenKwargs = true;
            }
        }

        base.Visit(node);
    }

    public override void Visit(ForStatement node)
    {
        if (locals.syntax is StarlarkFile)
        {
            Errorf(
                node,
                "for loops are not allowed at the top level. You may move it inside a function "
                    + "or use a comprehension, [f(x) for x in sequence]");
        }
        loopCount++;
        Visit(node.GetCollection());
        Assign(node.GetVars());
        VisitBlock(node.GetBody());
        if (loopCount <= 0)
        {
            throw new InvalidOperationException();
        }
        loopCount--;
    }

    public override void Visit(LoadStatement node)
    {
        if (locals.syntax is not StarlarkFile)
        {
            Errorf(node, "load statement not at top level");
        }
        // Skip base.Visit: don't revisit local Identifier as a use.
    }

    public override void Visit(FlowStatement node)
    {
        if (node.GetFlowKind() != TokenKind.PASS && loopCount <= 0)
        {
            Errorf(node, "{0} statement must be inside a for loop", node.GetFlowKind().ToDisplayString());
        }
        base.Visit(node);
    }

    public override void Visit(Comprehension node)
    {
        IReadOnlyList<Comprehension.Clause> clauses = node.GetClauses();

        // Following Python3, the first for clause is resolved outside the comprehension block. All
        // the other loops are resolved in the scope of their own bindings, permitting forward
        // references.
        var for0 = (Comprehension.For)clauses[0];
        Visit(for0.GetIterable());

        // A comprehension defines a distinct lexical block in the same function's frame. New
        // bindings go in the frame but aren't visible to the parent block.
        PushLocalBlock(node, this.locals.frame, this.locals.freevars);

        foreach (Comprehension.Clause clause in clauses)
        {
            if (clause is Comprehension.For forClause)
            {
                CreateBindingsForLHS(forClause.GetVars(), /* docComments= */ null);
            }
        }
        for (int i = 0; i < clauses.Count; i++)
        {
            Comprehension.Clause clause = clauses[i];
            if (clause is Comprehension.For forClause)
            {
                if (i > 0)
                {
                    Visit(forClause.GetIterable());
                }
                Assign(forClause.GetVars());
            }
            else
            {
                var ifClause = (Comprehension.If)clause;
                Visit(ifClause.GetCondition());
            }
        }
        Visit(node.GetBody());
        PopLocalBlock();
    }

    public override void Visit(DefStatement node)
    {
        AssertIsBound(node.GetIdentifier());
        // resolveFunction() recurses into the body.
        node.SetResolvedFunction(
            ResolveFunction(
                node,
                node.GetIdentifier().GetName(),
                node.GetIdentifier().GetStartLocation(),
                node.GetParameters(),
                node.GetReturnType(),
                node.GetBody()));
    }

    public override void Visit(LambdaExpression expr)
    {
        // resolveFunction() recurses into the body.
        expr.SetResolvedFunction(
            ResolveFunction(
                expr,
                "lambda",
                expr.GetStartLocation(),
                expr.GetParameters(),
                /* returnType= */ null,
                new List<Statement> { ReturnStatement.Make(expr.GetBody()) }));
    }

    public override void Visit(IfStatement node)
    {
        if (locals.syntax is StarlarkFile)
        {
            Errorf(
                node,
                "if statements are not allowed at the top level. You may move it inside a function "
                    + "or use an if expression (x if condition else y).");
        }
        base.Visit(node);
    }

    public override void Visit(AssignmentStatement node)
    {
        Visit(node.GetRHS());

        // Disallow: [e, ...] += rhs. Other bad cases are handled in assign.
        if (node.IsAugmented() && node.GetLHS() is ListExpression)
        {
            Errorf(
                node.GetOperatorLocation(),
                "cannot perform augmented assignment on a list or tuple expression");
        }

        if (node.GetType() != null && options.ResolveTypeSyntax)
        {
            Visit(node.GetType()!);
        }
        Assign(node.GetLHS());
    }

    public override void Visit(VarStatement node)
    {
        AssertIsBound(node.GetIdentifier());
        if (options.ResolveTypeSyntax)
        {
            Visit(node.GetType());
        }
    }

    public override void Visit(CastExpression node)
    {
        if (options.ResolveTypeSyntax)
        {
            Visit(node.GetType());
        }
        Visit(node.GetValue());
    }

    public override void Visit(IsInstanceExpression node)
    {
        Errorf(node, "isinstance() is not yet supported");
    }

    public override void Visit(TypeAliasStatement node)
    {
        if (locals.syntax is not StarlarkFile)
        {
            Errorf(node, "type alias statement not at top level");
        }

        if (options.ResolveTypeSyntax)
        {
            AssertIsBound(node.GetIdentifier());
            Visit(node.GetDefinition());
        }
    }

    // Resolves a non-binding identifier to an existing binding, or null.
    private Binding? Use(Identifier id)
    {
        string name = id.GetName();

        // Locally defined in this function, comprehension, or file block, or an enclosing one?
        Binding? bind = LookupLexical(name, locals);
        if (bind != null)
        {
            return bind;
        }

        // Defined at toplevel (global, predeclared, universal)?
        if (toplevel.TryGetValue(name, out bind))
        {
            return bind;
        }

        Scope scope;
        try
        {
            scope = module.Resolve(name);
        }
        catch (Undefined ex)
        {
            if (!Identifier.IsValid(name))
            {
                // If Identifier was created by Parser.makeErrorExpression, it contains misparsed
                // text. Ignore ex and report an appropriate error.
                Errorf(id, "contains syntax errors");
            }
            else if (ex.Candidates != null)
            {
                // Exception provided toplevel candidates. Show spelling suggestions of all symbols
                // in scope.
                string suggestion = SpellChecker.DidYouMean(name, GetAllSymbols(ex.Candidates));
                Errorf(id, "{0}{1}", ex.Message, suggestion);
            }
            else
            {
                Errorf(id, "{0}", ex.Message);
            }
            return null;
        }

        switch (scope)
        {
            case Scope.GLOBAL:
                bind = new Binding(scope, globals.Count, /* isSyntactic= */ false, id);
                // Accumulate globals in module.
                globals.Add(name);
                break;
            case Scope.PREDECLARED:
            case Scope.UNIVERSAL:
                bind = new Binding(scope, 0, /* isSyntactic= */ false, id); // index not used
                break;
            default:
                throw new InvalidOperationException("bad scope: " + scope);
        }
        toplevel[name] = bind;
        return bind;
    }

    // lookupLexical finds a lexically enclosing local binding of the name, plumbing it through
    // enclosing functions as needed.
    private static Binding? LookupLexical(string name, Block b)
    {
        if (b.bindings.TryGetValue(name, out Binding? bind))
        {
            return bind;
        }

        if (b.parent != null)
        {
            bind = LookupLexical(name, b.parent);
            if (bind != null)
            {
                // If a local binding was found in a parent block, and this block is a function, then
                // it is a free variable of this function and must be plumbed through.
                if (b.syntax is DefStatement || b.syntax is LambdaExpression)
                {
                    Scope scope = bind.GetScope();
                    if (scope == Scope.LOCAL || scope == Scope.FREE || scope == Scope.CELL)
                    {
                        if (scope == Scope.LOCAL)
                        {
                            bind.scope = Scope.CELL;
                        }
                        int index = b.freevars!.Count;
                        b.freevars.Add(bind);
                        bind = new Binding(Scope.FREE, index, /* isSyntactic= */ true, bind.first);
                    }
                }

                // Memoize, to avoid duplicate free vars and repeated walks.
                b.bindings[name] = bind;
            }
        }

        return bind;
    }

    // Common code for def, lambda.
    private Function ResolveFunction(
        Node syntax, // DefStatement or LambdaExpression
        string name,
        Location loc,
        IReadOnlyList<Parameter> parameters,
        Expression? returnType,
        IReadOnlyList<Statement> body)
    {
        // Resolve parameter types and default initializer exprs in enclosing environment.
        foreach (Parameter param in parameters)
        {
            if (param is Parameter.Optional)
            {
                Visit(param.GetDefaultValue()!);
            }
            if (param.GetType() != null && options.ResolveTypeSyntax)
            {
                Visit(param.GetType()!);
            }
        }
        // Resolve return type in enclosing environment.
        if (returnType != null && options.ResolveTypeSyntax)
        {
            Visit(returnType);
        }

        // Enter function block.
        var frame = new List<Binding>();
        var freevars = new List<Binding>();
        PushLocalBlock(syntax, frame, freevars);

        // Check parameter order and convert to run-time order:
        // positionals, keyword-only, *args, **kwargs.
        Parameter.Star? star = null;
        Parameter.StarStar? starStar = null;
        bool seenOptional = false;
        int numKeywordOnlyParams = 0;
        var paramsBuilder = new List<Parameter>(parameters.Count);
        foreach (Parameter param in parameters)
        {
            if (param is Parameter.Mandatory)
            {
                // e.g. id
                if (starStar != null)
                {
                    Errorf(
                        param,
                        "required parameter {0} may not follow **{1}",
                        param.GetName(),
                        starStar.GetName());
                }
                else if (star != null)
                {
                    numKeywordOnlyParams++;
                }
                else if (seenOptional)
                {
                    Errorf(
                        param,
                        "required positional parameter {0} may not follow an optional parameter",
                        param.GetName());
                }
                BindParam(paramsBuilder, param);
            }
            else if (param is Parameter.Optional)
            {
                // e.g. id = default
                seenOptional = true;
                if (starStar != null)
                {
                    Errorf(param, "optional parameter may not follow **{0}", starStar.GetName());
                }
                else if (star != null)
                {
                    numKeywordOnlyParams++;
                }
                BindParam(paramsBuilder, param);
            }
            else if (param is Parameter.Star pstar)
            {
                // * or *args
                if (starStar != null)
                {
                    Errorf(param, "* parameter may not follow **{0}", starStar.GetName());
                }
                else if (star != null)
                {
                    Errorf(param, "multiple * parameters not allowed");
                }
                else
                {
                    star = pstar;
                }
            }
            else
            {
                // **kwargs
                if (starStar != null)
                {
                    Errorf(param, "multiple ** parameters not allowed");
                }
                starStar = (Parameter.StarStar)param;
            }
        }

        // * or *args
        if (star != null)
        {
            if (star.GetIdentifier() != null)
            {
                BindParam(paramsBuilder, star);
            }
            else if (numKeywordOnlyParams == 0)
            {
                Errorf(star, "bare * must be followed by keyword-only parameters");
            }
        }

        // **kwargs
        if (starStar != null)
        {
            BindParam(paramsBuilder, starStar);
        }

        CreateBindingsForBlock(body);
        VisitAll(body);
        PopLocalBlock();

        return new Function(
            name,
            loc,
            paramsBuilder.ToImmutableArray(),
            body.ToImmutableArray(),
            star != null && star.GetIdentifier() != null,
            starStar != null,
            numKeywordOnlyParams,
            frame,
            freevars,
            globals);
    }

    private void BindParam(List<Parameter> paramsBuilder, Parameter param)
    {
        if (!Bind(param.GetIdentifier()!, /* isLoad= */ false, /* docComments= */ null))
        {
            Errorf(param, "duplicate parameter: {0}", param.GetName());
        }
        paramsBuilder.Add(param);
    }

    /// <summary>
    /// Process a binding use of a name by adding a binding to the current block if not already
    /// bound, and associate the identifier with it.
    /// </summary>
    /// <returns>true if the name was newly bound in this block, or false if it already existed.</returns>
    private bool Bind(Identifier id, bool isLoad, DocComments? docComments)
    {
        string name = id.GetName();
        bool isNew = false;
        Binding? bind;

        // outside any function/comprehension, and not a (local) load? => global binding.
        if (locals.syntax is StarlarkFile && !(isLoad && !options.LoadBindsGlobally))
        {
            if (!toplevel.TryGetValue(name, out bind))
            {
                // New global binding: add to module and to toplevel cache.
                isNew = true;
                bind = new Binding(Scope.GLOBAL, globals.Count, /* isSyntactic= */ true, id);
                globals.Add(name);
                if (docComments != null && docCommentsMap != null)
                {
                    docCommentsMap[name] = docComments;
                }
                toplevel[name] = bind;

                // Does this new global binding conflict with a file-local load binding?
                if (locals.bindings.TryGetValue(name, out Binding? prevLocal))
                {
                    GlobalLocalConflict(id, bind.scope, prevLocal); // global, local
                }
            }
            else
            {
                ToplevelRebinding(id, bind); // global, global
            }
        }
        else
        {
            // Binding is local to file, function, or comprehension.
            if (!locals.bindings.TryGetValue(name, out bind))
            {
                // New local binding: add to current block's bindings map, current function's frame.
                isNew = true;
                if (locals.syntax is Comprehension comprehension)
                {
                    // Assumption: any block nested in a comprehension is either another
                    // comprehension or has its own frame (e.g. a lambda).
                    bind = new ComprehensionBinding(locals.frame.Count, id, comprehension);
                }
                else
                {
                    bind = new Binding(Scope.LOCAL, locals.frame.Count, /* isSyntactic= */ true, id);
                }
                locals.bindings[name] = bind;
                locals.frame.Add(bind);
            }

            if (isLoad)
            {
                // Does this (file-local) load binding conflict with a previous one?
                if (!isNew)
                {
                    ToplevelRebinding(id, bind); // local, local
                }

                // ...or a previous global?
                if (toplevel.TryGetValue(name, out Binding? prev) && prev.scope == Scope.GLOBAL)
                {
                    GlobalLocalConflict(id, bind.scope, prev); // local, global
                }
            }
        }

        id.SetBinding(bind);

        return isNew;
    }

    // Report conflicting top-level bindings of same scope, unless options.allowToplevelRebinding.
    private void ToplevelRebinding(Identifier id, Binding prev)
    {
        if (!options.AllowToplevelRebinding)
        {
            Errorf(id, "'{0}' redeclared at top level", id.GetName());
            if (prev.isSyntactic)
            {
                Errorf(prev.first, "'{0}' previously declared here", id.GetName());
            }
        }
    }

    // Report global/local scope conflict on top-level bindings.
    private void GlobalLocalConflict(Identifier id, Scope scope, Binding prev)
    {
        string newqual = scope == Scope.GLOBAL ? "global" : "file-local";
        string oldqual = prev.GetScope() == Scope.GLOBAL ? "global" : "file-local";
        Errorf(id, "conflicting {0} declaration of '{1}'", newqual, id.GetName());
        if (prev.isSyntactic)
        {
            Errorf(prev.first, "'{0}' previously declared as {1} here", id.GetName(), oldqual);
        }
    }

    // Returns the union of accessible local and top-level symbols.
    private ISet<string> GetAllSymbols(ISet<string> predeclared)
    {
        var all = new HashSet<string>();
        for (Block? b = locals; b != null; b = b.parent)
        {
            all.UnionWith(b.bindings.Keys);
        }
        all.UnionWith(predeclared);
        all.UnionWith(toplevel.Keys);
        return all;
    }

    // Report an error if a load statement appears after another kind of statement.
    private void CheckLoadAfterStatement(IReadOnlyList<Statement> statements)
    {
        Statement? firstStatement = null;

        foreach (Statement statement in statements)
        {
            // Ignore string literals (e.g. docstrings).
            if (statement is ExpressionStatement exprStmt
                && exprStmt.GetExpression() is StringLiteral)
            {
                continue;
            }

            if (statement is LoadStatement)
            {
                if (firstStatement == null)
                {
                    continue;
                }
                Errorf(statement, "load statements must appear before any other statement");
                Errorf(firstStatement, "\tfirst non-load statement appears here");
            }

            firstStatement ??= statement;
        }
    }

    /// <summary>
    /// Performs static checks, including resolution of identifiers in <paramref name="file"/> in the
    /// environment defined by <paramref name="module"/>. Syntax must be resolved before it is
    /// evaluated.
    /// </summary>
    public static void ResolveFile(StarlarkFile file, IModule module)
    {
        var r = new Resolver(file.errors, module, file.GetOptions(), file.docCommentsMap);
        IReadOnlyList<Statement> stmts = file.GetStatements();

        // Check that load statements are on top.
        if (r.options.RequireLoadStatementsFirst)
        {
            r.CheckLoadAfterStatement(stmts);
        }

        var frame = new List<Binding>();
        r.PushLocalBlock(file, frame, /* freevars= */ null);

        // First pass: creating bindings for statements in this block.
        r.CreateBindingsForBlock(stmts);

        // Second pass: visit all references.
        r.VisitAll(stmts);

        r.PopLocalBlock();

        // If the final statement is an expression, synthesize a return statement.
        int n = stmts.Count;
        ImmutableArray<Statement> bodyStmts;
        if (n > 0 && stmts[n - 1] is ExpressionStatement lastExprStmt)
        {
            Expression expr = lastExprStmt.GetExpression();
            var builder = ImmutableArray.CreateBuilder<Statement>(n);
            for (int i = 0; i < n - 1; i++)
            {
                builder.Add(stmts[i]);
            }
            builder.Add(ReturnStatement.Make(expr));
            bodyStmts = builder.ToImmutable();
        }
        else
        {
            bodyStmts = stmts.ToImmutableArray();
        }

        // Annotate with resolved information about the toplevel function.
        file.SetResolvedFunction(
            new Function(
                "<toplevel>",
                file.GetStartLocation(),
                /* params= */ ImmutableArray<Parameter>.Empty,
                /* body= */ bodyStmts,
                /* hasVarargs= */ false,
                /* hasKwargs= */ false,
                /* numKeywordOnlyParams= */ 0,
                frame,
                /* freevars= */ new List<Binding>(),
                r.globals));
    }

    /// <summary>
    /// Performs static checks, including resolution of identifiers in <paramref name="expr"/> in the
    /// environment defined by <paramref name="module"/>.
    /// </summary>
    /// <exception cref="SyntaxError.Exception">on resolution error.</exception>
    public static Function ResolveExpr(Expression expr, IModule module, FileOptions options)
    {
        var errors = new List<SyntaxError>();
        var r = new Resolver(errors, module, options, /* docCommentsMap= */ null);

        var frame = new List<Binding>();
        r.PushLocalBlock(null, frame, /* freevars= */ null); // for bindings in list comprehensions
        r.Visit(expr);
        r.PopLocalBlock();

        if (errors.Count != 0)
        {
            throw new SyntaxError.Exception(errors);
        }

        // Return no-arg function that computes the expression.
        return new Function(
            "<expr>",
            expr.GetStartLocation(),
            /* params= */ ImmutableArray<Parameter>.Empty,
            ImmutableArray.Create<Statement>(ReturnStatement.Make(expr)),
            /* hasVarargs= */ false,
            /* hasKwargs= */ false,
            /* numKeywordOnlyParams= */ 0,
            frame,
            /* freevars= */ new List<Binding>(),
            r.globals);
    }

    private void PushLocalBlock(Node? syntax, List<Binding> frame, List<Binding>? freevars)
    {
        locals = new Block(locals, syntax, frame, freevars);
    }

    private void PopLocalBlock()
    {
        locals = locals.parent!;
    }
}
