package(default_visibility = ["//visibility:public"])

java_library(
    name = "util",
    srcs = glob(["**/*.java"]),
    deps = [
        "//java/com/google/copybara:base",
        "//java/com/google/copybara/util/console",
        "//third_party:guava",
        "//third_party:shell",
        "//third_party:skylark-lang",
    ],
)
