# GCB configuration file
# To learn more about GCB, go to https://cloud.google.com/container-builder/docs/
steps:
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - "--destination=gcr.io/$PROJECT_ID/ci:${_BAZEL_SHA256}"
  - "--context=dir:///workspace"
  - "--dockerfile=ci.Dockerfile"
  - "--build-arg=BAZEL_VERSION=@sha256:${_BAZEL_SHA256}"
  - "--cache=true"
- name: gcr.io/$PROJECT_ID/ci:${_BAZEL_SHA256}
  args: ["test",  "--java_language_version=11", "--tool_java_language_version=11", "--java_runtime_version=remotejdk_11", "--test_output=errors", "--subcommands",  "--sandbox_tmpfs_path=/tmp", "--jobs=1000", "--", "..."]
options:
  machine_type: N1_HIGHCPU_32
substitutions:
  _BAZEL_SHA256: 0a9fb6c7bb0db386888a26940e87829ffad4d2a6bc12bcc32523670ef9ea6505
timeout: 30m
