# GCB configuration file
# To learn more about GCB, go to https://cloud.google.com/container-builder/docs/
steps:
- name: 'gcr.io/cloud-builders/docker:latest'
  args:
  - "build"
  - "-f"
  - "ci.Dockerfile"
  - "--build-arg"
  - "BAZEL_VERSION=@sha256:${_BAZEL_SHA256}"
  - "-t"
  - "ci"
  - "."
# The /builder folder is mounted across steps but owned by root:root
# HOME=/builder/home
# https://github.com/GoogleCloudPlatform/cloud-builders/issues/641
- name: 'ubuntu'
  args: ["chmod", "-R", "777", "/builder"]
# Bazel 7.2 symlinks the workspace in a way that causes nested gits in some of our tests
- name: 'ubuntu'
  args: ["rm", "-rf", "/workspace/.git"]
- name: 'ci'
  args: ["test", "--enable_bzlmod=true", "--java_language_version=21", "--tool_java_language_version=21", "--java_runtime_version=remotejdk_21", "--tool_java_runtime_version=remotejdk_21","--test_output=errors", "--subcommands",  "--sandbox_tmpfs_path=/tmp", "--jobs=1000", "--", "..."]
options:
  machine_type: N1_HIGHCPU_32
substitutions:
  _BAZEL_SHA256: fedbeb377c97000d1ba27cfdcc22e1025303b4b0abffcd940a94250147fe0fcf
timeout: 30m
