# Copyright 2016 Google Inc. All Rights Reserved.

sh_test(
    name = "tool_test",
    srcs = ["tool_test.sh"],
    data = [
            "//java/com/google/copybara:copybara",
            "//third_party/bazel/bashunit",
    ])
