/*
 * Copyright (C) 2023 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Copybara;
using Copybara.Exceptions;

namespace Copybara.Util;

/// <summary>
/// ConsistencyFile represents the difference between what exists in the destination files and the
/// output of an import created by Copybara. This will only be different when using merge import
/// mode, because otherwise the destination files will be overwritten and there will be no
/// difference.
/// </summary>
public sealed class ConsistencyFile
{
    private const string RegenerateErrPrompt =
        "Consider regenerating the consistency file using the regenerate command.";

    private const string Header = "# This file is generated by Copybara.\n# Do not edit.\n";

    private const string HashDelimiter = "--hash-delimiter--";

    private readonly ImmutableDictionary<string, string> _fileHashes;
    private readonly byte[] _diffContent;
    private readonly string? _workflowInfo;

    public ConsistencyFile(ImmutableDictionary<string, string> fileHashes, byte[] diffContent)
        : this(fileHashes, diffContent, null)
    {
    }

    public ConsistencyFile(
        ImmutableDictionary<string, string> fileHashes, byte[] diffContent, string? workflowInfo)
    {
        _fileHashes = fileHashes;
        _diffContent = diffContent;
        _workflowInfo = workflowInfo;
    }

    /// <summary>
    /// Create a ConsistencyFile object from two folders containing separate versions of the
    /// repository.
    /// </summary>
    public static ConsistencyFile Generate(
        string baseline,
        string destination,
        HashAlgorithmName hashFunction,
        IReadOnlyDictionary<string, string> environment,
        bool verbose) =>
        Generate(baseline, destination, hashFunction, environment, verbose, (string?)null);

    public static ConsistencyFile Generate(
        string baseline,
        string destination,
        HashAlgorithmName hashFunction,
        IReadOnlyDictionary<string, string> environment,
        bool verbose,
        string configPath,
        string workflowName) =>
        Generate(
            baseline,
            destination,
            hashFunction,
            environment,
            verbose,
            ExtractWorkflowInfo(configPath, workflowName));

    public static ConsistencyFile Generate(
        string baseline,
        string destination,
        HashAlgorithmName hashFunction,
        IReadOnlyDictionary<string, string> environment,
        bool verbose,
        string configPath,
        string workflowName,
        bool excludeBuildFiles) =>
        Generate(
            baseline,
            destination,
            hashFunction,
            environment,
            verbose,
            ExtractWorkflowInfo(configPath, workflowName),
            excludeBuildFiles);

    public static ConsistencyFile Generate(
        string baseline,
        string destination,
        HashAlgorithmName hashFunction,
        IReadOnlyDictionary<string, string> environment,
        bool verbose,
        string? workflowInfo) =>
        Generate(baseline, destination, hashFunction, environment, verbose, workflowInfo, false);

    public static ConsistencyFile Generate(
        string baseline,
        string destination,
        HashAlgorithmName hashFunction,
        IReadOnlyDictionary<string, string> environment,
        bool verbose,
        string? workflowInfo,
        bool excludeBuildFiles)
    {
        byte[] diff = DiffUtil.DiffWithIgnoreCrAtEol(baseline, destination, verbose, environment);
        if (excludeBuildFiles)
        {
            diff = Encoding.UTF8.GetBytes(
                DiffUtil.FilterDiff(diff, path => !path.EndsWith("BUILD", StringComparison.Ordinal)));
        }
        var destinationHashes = ComputeFileHashes(destination, hashFunction, excludeBuildFiles);
        var baselineFileNames = GetFileNames(baseline, excludeBuildFiles);

        var filesetDiff = CalculateFileSetDiff(destinationHashes, baselineFileNames);

        if (!filesetDiff.DestinationOnly.IsEmpty || !filesetDiff.OriginOnly.IsEmpty)
        {
            string message =
                "Error: Detected full-file diffs when generating consistency file: "
                + $"{filesetDiff}. Please adjust destination or origin globs to exclude these"
                + " files.\n";
            var extraDotFiles = filesetDiff.DestinationOnly
                .Where(file => PathOps.GetFileName(file).StartsWith('.'))
                .ToImmutableHashSet();
            var origFiles = filesetDiff.DestinationOnly
                .Where(file => file.EndsWith(".orig", StringComparison.Ordinal))
                .ToImmutableHashSet();

            if (!extraDotFiles.IsEmpty)
            {
                message +=
                    "If using an hg-based VCS, dot files may not be tracked by the destination, but"
                    + " still be present in the workspace.\n";
            }
            if (!origFiles.IsEmpty)
            {
                message +=
                    "If using an hg-based VCS, '.orig' files may need to be cleaned up manually in"
                    + " the destination.\n";
            }
            throw new ValidationException(message);
        }

        return new ConsistencyFile(destinationHashes, diff, workflowInfo);
    }

    /// <summary>The set difference between destination and baseline file sets.</summary>
    public sealed record FileSetDiff(
        ImmutableArray<string> DestinationOnly, ImmutableArray<string> OriginOnly)
    {
        public override string ToString() =>
            $"FileSetDiff[destinationOnly={{{string.Join(", ", DestinationOnly)}}},"
            + $" originOnly={{{string.Join(", ", OriginOnly)}}}]";
    }

    public static FileSetDiff CalculateFileSetDiff(
        ImmutableDictionary<string, string> destinationHashes,
        ImmutableArray<string> baselineFileNames)
    {
        var destinationFileSet = destinationHashes.Keys.ToImmutableHashSet();
        var baselineFileSet = baselineFileNames.ToImmutableHashSet();

        var destinationOnly = destinationFileSet.Except(baselineFileSet).OrderBy(s => s, StringComparer.Ordinal).ToImmutableArray();
        var originOnly = baselineFileSet.Except(destinationFileSet).OrderBy(s => s, StringComparer.Ordinal).ToImmutableArray();

        return new FileSetDiff(destinationOnly, originOnly);
    }

    public static ConsistencyFile GenerateNoDiff(
        string contents, HashAlgorithmName hashFunction, string configPath, string workflowName) =>
        GenerateNoDiff(contents, hashFunction, configPath, workflowName, false);

    public static ConsistencyFile GenerateNoDiff(
        string contents,
        HashAlgorithmName hashFunction,
        string configPath,
        string workflowName,
        bool excludeBuildFiles) =>
        new(
            ComputeFileHashes(contents, hashFunction, excludeBuildFiles),
            Array.Empty<byte>(),
            ExtractWorkflowInfo(configPath, workflowName));

    public static ConsistencyFile GenerateNoDiff(string contents, HashAlgorithmName hashFunction) =>
        GenerateNoDiff(contents, hashFunction, false);

    public static ConsistencyFile GenerateNoDiff(
        string contents, HashAlgorithmName hashFunction, bool excludeBuildFiles) =>
        new(ComputeFileHashes(contents, hashFunction, excludeBuildFiles), Array.Empty<byte>());

    private static ImmutableArray<string> GetFileNames(string directory, bool excludeBuildFiles)
    {
        var namesBuilder = ImmutableArray.CreateBuilder<string>();
        foreach (var file in EnumerateNonSymlinkFiles(directory))
        {
            if (excludeBuildFiles && PathOps.GetFileName(file) == "BUILD")
            {
                continue;
            }
            namesBuilder.Add(PathOps.Relativize(directory, file));
        }
        return namesBuilder.ToImmutable();
    }

    private static ImmutableDictionary<string, string> ComputeFileHashes(
        string directory, HashAlgorithmName hashFunction, bool excludeBuildFiles)
    {
        var hashesBuilder = ImmutableDictionary.CreateBuilder<string, string>();
        foreach (var file in EnumerateNonSymlinkFiles(directory))
        {
            if (excludeBuildFiles && PathOps.GetFileName(file) == "BUILD")
            {
                continue;
            }
            hashesBuilder[PathOps.Relativize(directory, file)] = HashFile(file, hashFunction);
        }
        return hashesBuilder.ToImmutable();
    }

    private static string MustReadLine(TextReader reader)
    {
        string? line = reader.ReadLine();
        if (line == null)
        {
            throw new IOException("failed to parse consistency file: unexpected end of file");
        }
        return line;
    }

    private static string MustReadUncommentedLine(TextReader reader)
    {
        string line = MustReadLine(reader);
        while (line.StartsWith('#'))
        {
            line = MustReadLine(reader);
        }
        return line;
    }

    public static ConsistencyFile FromBytes(byte[] bytes)
    {
        using var reader = new StringReader(Encoding.UTF8.GetString(bytes));
        var fileHashesBuilder = ImmutableDictionary.CreateBuilder<string, string>();

        string line = MustReadUncommentedLine(reader);
        while (line != HashDelimiter)
        {
            int idx = line.IndexOf(": ", StringComparison.Ordinal);
            if (idx < 0)
            {
                throw new IOException(
                    "failed to parse consistency file hashes: unexpected number of elements");
            }
            string path = line.Substring(0, idx);
            string hash = line.Substring(idx + 2);
            ValidateParsedPathValue(path);
            ValidateParsedHashValue(hash);
            fileHashesBuilder[path] = hash;

            line = MustReadUncommentedLine(reader);
        }

        var diffContentOut = new StringBuilder();
        string? diffLine = reader.ReadLine();
        while (diffLine != null)
        {
            diffContentOut.Append(diffLine).Append('\n');
            diffLine = reader.ReadLine();
        }

        return new ConsistencyFile(
            fileHashesBuilder.ToImmutable(), Encoding.UTF8.GetBytes(diffContentOut.ToString()));
    }

    public ImmutableDictionary<string, string> GetFileHashes() => _fileHashes;

    internal byte[] GetDiffContent() => (byte[])_diffContent.Clone();

    public byte[] ToBytes()
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        if (_workflowInfo != null)
        {
            sb.Append($"# Workflow: {_workflowInfo}\n");
        }

        foreach (var entry in _fileHashes
                     .OrderBy(e => e.Key, StringComparer.Ordinal)
                     .ThenBy(e => e.Value, StringComparer.Ordinal))
        {
            sb.Append($"{entry.Key}: {entry.Value}\n");
        }
        sb.Append(HashDelimiter + "\n");

        var headerBytes = Encoding.UTF8.GetBytes(sb.ToString());
        var result = new byte[headerBytes.Length + _diffContent.Length];
        Buffer.BlockCopy(headerBytes, 0, result, 0, headerBytes.Length);
        Buffer.BlockCopy(_diffContent, 0, result, headerBytes.Length, _diffContent.Length);
        return result;
    }

    /// <summary>
    /// Applies the diff contained in the patch in reverse on the input destination directory,
    /// obtaining the origin directory sans any destination-only changes.
    /// </summary>
    public void ReversePatches(string dir, IReadOnlyDictionary<string, string> environment)
    {
        AutoPatchUtil.ReversePatch(dir, GetDiffContent(), environment);
    }

    /// <summary>Functional interface for obtaining a hash, given a file.</summary>
    public interface IHashGetter
    {
        string GetHashString(string filePath);
    }

    /// <summary>
    /// Return a <see cref="IHashGetter"/> that obtains the hash by reading the file at the path
    /// relative to the passed in directory and hashing it.
    /// </summary>
    public static IHashGetter SimpleHashGetter(string dir, HashAlgorithmName hashFunction) =>
        new FuncHashGetter(path => HashFile(PathOps.Resolve(dir, path), hashFunction));

    private sealed class FuncHashGetter : IHashGetter
    {
        private readonly Func<string, string> _func;
        public FuncHashGetter(Func<string, string> func) => _func = func;
        public string GetHashString(string filePath) => _func(filePath);
    }

    /// <summary>A utility method for obtaining a list of files from a directory.</summary>
    public static ImmutableHashSet<string> FilesInDir(string dir) =>
        Directory.Exists(dir)
            ? Directory.EnumerateFiles(dir, "*", SearchOption.AllDirectories)
                .Select(f => PathOps.Relativize(dir, f))
                .ToImmutableHashSet()
            : ImmutableHashSet<string>.Empty;

    /// <summary>
    /// Applies some checks to verify that a directory matches the state of the destination directory
    /// used when this Consistency file was created.
    /// </summary>
    public void ValidateDirectory(ImmutableHashSet<string> files, IHashGetter hashFetcher)
    {
        var directoryFiles = files.Select(PathOps.Normalize).ToImmutableHashSet();

        var consistencyFileHashes = _fileHashes.Keys.ToImmutableHashSet();
        var directoryOnlyFiles = directoryFiles
            .Where(file => !consistencyFileHashes.Contains(file))
            .ToImmutableHashSet();

        if (!directoryOnlyFiles.IsEmpty)
        {
            throw new ValidationException(
                "Encountered files in directory not present in ConsistencyFile: "
                + $"{{{string.Join(", ", directoryOnlyFiles)}}}. {RegenerateErrPrompt}");
        }

        var consistencyFileOnlyHashes = consistencyFileHashes
            .Where(file => !directoryFiles.Contains(file))
            .ToImmutableHashSet();

        if (!consistencyFileOnlyHashes.IsEmpty)
        {
            throw new ValidationException(
                "Encountered files not found in directory but present in ConsistencyFile: "
                + $"{{{string.Join(", ", consistencyFileHashes)}}}. {RegenerateErrPrompt}");
        }

        foreach (var hashEntry in _fileHashes)
        {
            string fileName = hashEntry.Key;
            string expectedHash = hashEntry.Value;
            string actualHash = hashFetcher.GetHashString(fileName);
            if (expectedHash != actualHash)
            {
                throw new ValidationException(
                    $"File {fileName} has hash value {expectedHash} in ConsistencyFile but"
                    + $" {actualHash} in directory. {RegenerateErrPrompt}");
            }
        }
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(this, obj))
        {
            return true;
        }
        if (obj is not ConsistencyFile that)
        {
            return false;
        }
        if (_fileHashes.Count != that._fileHashes.Count
            || _fileHashes.Any(kv => !that._fileHashes.TryGetValue(kv.Key, out var v) || v != kv.Value))
        {
            return false;
        }
        return _diffContent.AsSpan().SequenceEqual(that._diffContent);
    }

    public override int GetHashCode() =>
        HashCode.Combine(_fileHashes.Count, _diffContent.Length);

    public override string ToString() =>
        $"{{{string.Join(", ", _fileHashes.Select(kv => $"{kv.Key}={kv.Value}"))}}}\n"
        + $"{Encoding.UTF8.GetString(_diffContent)}\n";

    private static void ValidateParsedPathValue(string path)
    {
        if (path.IndexOfAny(System.IO.Path.GetInvalidPathChars()) >= 0)
        {
            throw new ValidationException($"Parsed path value is invalid: {path}.");
        }
    }

    private static void ValidateParsedHashValue(string hash)
    {
        // A hash is a hex string; validate it can be parsed as such.
        foreach (char c in hash)
        {
            if (!Uri.IsHexDigit(c))
            {
                throw new ValidationException($"Parsed hash value is invalid: {hash}.");
            }
        }
    }

    private static string ExtractWorkflowInfo(string configPath, string workflowName) =>
        $"{configPath}:{workflowName}";

    private static IEnumerable<string> EnumerateNonSymlinkFiles(string directory)
    {
        if (!Directory.Exists(directory))
        {
            yield break;
        }
        foreach (var file in Directory.EnumerateFiles(directory, "*", SearchOption.AllDirectories))
        {
            var attrs = File.GetAttributes(file);
            if ((attrs & FileAttributes.ReparsePoint) != 0)
            {
                // skip symbolic links
                continue;
            }
            yield return file;
        }
    }

    private static string HashFile(string file, HashAlgorithmName hashFunction)
    {
        using var stream = File.OpenRead(file);
        using var algo = CreateHashAlgorithm(hashFunction);
        byte[] hash = algo.ComputeHash(stream);
        return Convert.ToHexStringLower(hash);
    }

    private static HashAlgorithm CreateHashAlgorithm(HashAlgorithmName name)
    {
        if (name == HashAlgorithmName.SHA256)
        {
            return SHA256.Create();
        }
        if (name == HashAlgorithmName.SHA1)
        {
            return SHA1.Create();
        }
        if (name == HashAlgorithmName.SHA512)
        {
            return SHA512.Create();
        }
        if (name == HashAlgorithmName.MD5)
        {
            return MD5.Create();
        }
        var created = CryptoConfig.CreateFromName(name.Name!) as HashAlgorithm;
        return created ?? SHA256.Create();
    }
}
