package(default_visibility = ["//visibility:public"])

java_library(
    name = "console",
    srcs = glob(["**/*.java"]),
    deps = [
        "//third_party:guava",
        "//third_party:jsr305",
    ],
)
