package(default_visibility = ["//visibility:public"])

licenses(["unencumbered"])  # Owned by Google. No external contributions

java_library(
    name = "console",
    srcs = glob(["**/*.java"]),
    deps = [
        "//third_party:guava",
        "//third_party:jsr305",
    ],
)
