# Copyright 2016 Google Inc. All Rights Reserved.

java_library(
    name = "testing",
    srcs = glob(["**/*.java"]),
    deps = [
        "//java/com/google/copybara:copybara_lib",
        "//third_party:truth",
    ],
    visibility = ["//visibility:public"],
)
