/*
 * Copyright (C) 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Collections.Immutable;
using System.Globalization;
using Copybara.Common;
using Copybara.Effect;
using Copybara.Exceptions;
using Copybara.Revision;
using Copybara.Util.Console;
using EffectType = Copybara.Effect.DestinationEffect.EffectType;

namespace Copybara;

/// <summary>
/// Per-mode run logic for <see cref="WorkflowMode"/>.
///
/// <para>In upstream Java each <c>WorkflowMode</c> enum constant carries its own <c>run</c>
/// implementation. C# enums cannot carry behavior, so the dispatch and the shared helpers
/// (<c>filterChanges</c>, <c>maybeGetLastRev</c>, <c>isHistorySupported</c>, etc.) live here and are
/// dispatched from <see cref="Workflow{O,D}.Run"/> via <see cref="Run{O,D}"/>.</para>
/// </summary>
public static class WorkflowModeRunner
{
    /// <summary>Dispatches to the run logic for <paramref name="mode"/>.</summary>
    public static void Run<O, D>(WorkflowMode mode, WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        switch (mode)
        {
            case WorkflowMode.Squash:
                RunSquash(runHelper);
                break;
            case WorkflowMode.Iterative:
                RunIterative(runHelper);
                break;
            case WorkflowMode.ChangeRequest:
                RunChangeRequestMode(runHelper);
                break;
            case WorkflowMode.ChangeRequestFromSot:
                RunChangeRequestFromSot(runHelper);
                break;
            default:
                throw new InvalidOperationException("Unexpected workflow mode: " + mode);
        }
    }

    /// <summary>Create a single commit in the destination with new tree state.</summary>
    private static void RunSquash<O, D>(WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        IReadOnlyList<Change<O>> detectedChanges = ImmutableArray<Change<O>>.Empty;
        IReadOnlyDictionary<Change<O>, Change<O>> conditionalChanges =
            ImmutableDictionary<Change<O>, Change<O>>.Empty;
        O? current = runHelper.GetResolvedRef();
        O? lastRev = null;
        if (IsHistorySupported(runHelper))
        {
            lastRev = MaybeGetLastRev(runHelper);
            if (runHelper.WorkflowOptions().ImportSameVersion)
            {
                current = lastRev; // Import the last imported version.
            }
            else
            {
                Origin.ChangesResponse<O> response = runHelper.GetChanges(lastRev, current!);
                if (response.IsEmpty())
                {
                    ManageNoChangesDetectedForSquash(
                        runHelper, current!, lastRev, response.GetEmptyReason());
                }
                else
                {
                    detectedChanges = response.GetChanges();
                    conditionalChanges = response.GetConditionalChanges();
                }
            }
        }

        var metadata = new Metadata(
            runHelper.GetChangeMessage("Project import generated by Copybara.\n"),
            // SQUASH workflows always use the default author if it was not forced.
            runHelper.GetFinalAuthor(runHelper.GetAuthoring().GetDefaultAuthor()),
            ImmutableListMultimap<string, string>.Empty);

        runHelper.MaybeValidateRepoInLastRevState(metadata);

        // Don't replace helperForChanges with runHelper since origin_files could be potentially
        // different in the helper for the current change.
        ChangeMigrator<O, D> helperForChanges = detectedChanges.Count == 0
            ? runHelper.GetDefaultMigrator()
            : runHelper.GetMigratorForChange(detectedChanges[^1]);

        // Remove changes that don't affect origin_files
        IReadOnlyList<Change<O>> changes = FilterChanges(
            detectedChanges, conditionalChanges, helperForChanges);
        if (changes.Count == 0
            && IsHistorySupported(runHelper)
            && !runHelper.WorkflowOptions().ImportSameVersion)
        {
            ManageNoChangesDetectedForSquash(
                runHelper, current!, lastRev, Origin.EmptyReason.NoChanges);
        }

        // Try to use the latest change that affected the origin_files roots instead of the current
        // revision, that could be an unrelated change.
        current = changes.Count == 0 ? current : changes[^1].GetRevision();

        if (runHelper.IsSquashWithoutHistory())
        {
            changes = ImmutableArray<Change<O>>.Empty;
        }
        ValidationException.CheckCondition(
            current != null,
            "Could not process ref. If using --same-version flag, please either (1) check our"
                + " METADATA file to confirm version is properly formatted or (2) also use the"
                + " --last-rev flag to manually specify");
        helperForChanges.Migrate(
            current!,
            lastRev,
            runHelper.GetConsole(),
            metadata,
            // Squash notes an Skylark API expect last commit to be the first one.
            new Changes(changes.Reverse().Cast<object>(), Array.Empty<object>()),
            /* destinationBaseline= */ null,
            runHelper.GetResolvedRef(),
            runHelper.GetOriginBaselineForMergeImport(lastRev));
    }

    /// <summary>Import each origin change individually.</summary>
    private static void RunIterative<O, D>(WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        O? lastRev = runHelper.GetLastRev();
        Origin.ChangesResponse<O> changesResponse =
            runHelper.GetChanges(lastRev, runHelper.GetResolvedRef());
        if (changesResponse.IsEmpty())
        {
            ValidationException.CheckCondition(
                changesResponse.GetEmptyReason() != Origin.EmptyReason.UnrelatedRevisions,
                "last imported revision %s is not ancestor of requested revision %s",
                lastRev!,
                runHelper.GetResolvedRef());
            throw new EmptyChangeException(
                "No new changes to import for resolved ref: "
                    + runHelper.GetResolvedRef().AsString());
        }
        int changeNumber = 1;

        var changes = changesResponse.GetChanges().ToImmutableArray();
        int limit = changes.Length;
        if (runHelper.WorkflowOptions().IterativeLimitChanges < changes.Length)
        {
            limit = runHelper.WorkflowOptions().IterativeLimitChanges;
            runHelper.GetConsole().Info(string.Format(
                CultureInfo.InvariantCulture,
                "Importing first {0} change(s) out of {1}",
                limit, changes.Length));
        }

        runHelper.MaybeValidateRepoInLastRevState(metadata: null);

        bool useIterativeMergeImport = runHelper.GetGeneralOptions()
            .IsTemporaryFeature("experimental_iterative_merge_import", false);
        O? originBaseline =
            useIterativeMergeImport ? runHelper.GetOriginBaselineForMergeImport(lastRev) : null;

        if (useIterativeMergeImport && runHelper.IsMergeImport())
        {
            runHelper.GetConsole().Warn(
                "Iterative Merge Import is experimental. Please monitor the generated changelists.");
        }

        var migrated = new LinkedList<object>();
        int migratedChanges = 0;
        int index = 0;
        while (index < changes.Length && migratedChanges < limit)
        {
            Change<O> change = changes[index];
            string prefix = string.Format(
                CultureInfo.InvariantCulture,
                "Change {0} of {1} ({2}): ",
                changeNumber, Math.Min(changes.Length, limit), change.GetRevision().AsString());

            bool errors = false;
            using (runHelper.Profiler().Start(change.GetRevision().AsString()))
            {
                var current = new object[] { change };
                ChangeMigrator<O, D> migrator = runHelper.GetMigratorForChange(change);
                if (migrator.SkipChange(change))
                {
                    index++;
                    continue;
                }
                IReadOnlyList<DestinationEffect> result;
                try
                {
                    result = migrator.Migrate(
                        change.GetRevision(),
                        lastRev,
                        new PrefixConsole(prefix, runHelper.GetConsole()),
                        new Metadata(
                            runHelper.GetChangeMessage(change.GetMessage()),
                            runHelper.GetFinalAuthor(change.GetAuthor()),
                            ImmutableListMultimap<string, string>.Empty),
                        new Changes(current, migrated),
                        /* destinationBaseline= */ null,
                        // Use the current change since we might want to create different reviews in
                        // the destination.
                        change.GetRevision(),
                        originBaseline);
                    migratedChanges++;
                    foreach (var effect in result)
                    {
                        if (effect.Type != EffectType.NOOP)
                        {
                            errors |= effect.Errors.Count != 0;
                        }
                    }
                }
                catch (EmptyChangeException e)
                {
                    runHelper.GetConsole().WarnFmt(
                        "Migration of origin revision '%s' resulted in an empty change in the"
                            + " destination: %s",
                        change.GetRevision().AsString(), e.Message);
                }
                catch (Exception e) when (e is ValidationException or RepoException)
                {
                    runHelper.GetConsole().ErrorFmt(
                        "Migration of origin revision '%s' failed with error: %s",
                        change.GetRevision().AsString(), e.Message);
                    throw;
                }
            }
            migrated.AddFirst(change);

            bool hasNext = index + 1 < changes.Length;
            if (errors && hasNext)
            {
                // Use the regular console to log prompt and final message, easier to spot.
                if (!runHelper.GetConsole().PromptConfirmation("Continue importing next change?"))
                {
                    string message = string.Format(
                        CultureInfo.InvariantCulture,
                        "Iterative workflow aborted by user after: {0}",
                        prefix);
                    runHelper.GetConsole().Warn(message);
                    throw new ChangeRejectedException(message);
                }
            }
            if (useIterativeMergeImport)
            {
                lastRev = change.GetRevision();
                originBaseline = change.GetRevision();
            }
            changeNumber++;
            index++;
        }
        if (migratedChanges == 0)
        {
            throw new EmptyChangeException(
                string.Format(
                    CultureInfo.InvariantCulture,
                    "Iterative workflow produced no changes in the destination for resolved ref: {0}",
                    runHelper.GetResolvedRef().AsString()));
        }
        // logger.atInfo().log("Imported %d change(s) out of %d", migratedChanges, changes.Length);
    }

    /// <summary>
    /// Import an origin tree state diffed by a common parent in destination. This could be a GH Pull
    /// Request, a Gerrit Change, etc.
    /// </summary>
    private static void RunChangeRequestMode<O, D>(WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        ValidationException.CheckCondition(
            runHelper.DestinationSupportsPreviousRef(),
            "'%s' is incompatible with destinations that don't support history (For example"
                + " folder.destination)",
            WorkflowMode.ChangeRequest);
        string originLabelName = runHelper.GetLabelNameWhenOrigin();
        Origin.Baseline<O>? baseline =
            string.IsNullOrEmpty(runHelper.WorkflowOptions().ChangeBaseline)
                ? runHelper.GetOriginReader().FindBaseline(runHelper.GetResolvedRef(), originLabelName)
                : new Origin.Baseline<O>(
                    runHelper.WorkflowOptions().ChangeBaseline, /*originRevision=*/ null);

        RunChangeRequest(
            runHelper,
            baseline,
            runHelper.WorkflowOptions().BaselineForMergeImport == null
                ? (baseline
                    ?? throw new ValidationException(
                        "Cannot read origin revision from baseline, please specify the baseline"
                            + " using the --baseline-for-merge-import flag."))
                    .GetOriginRevision()
                : runHelper.OriginResolveLastRev(runHelper.WorkflowOptions().BaselineForMergeImport!));
    }

    /// <summary>Import from the Source-of-Truth.</summary>
    private static void RunChangeRequestFromSot<O, D>(WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        IReadOnlyList<O> originBaselines;
        if (string.IsNullOrEmpty(runHelper.WorkflowOptions().ChangeBaseline))
        {
            originBaselines = runHelper.GetOriginReader().FindBaselinesWithoutLabel(
                runHelper.GetResolvedRef(),
                runHelper.WorkflowOptions().ChangeRequestFromSotLimit);
        }
        else
        {
            originBaselines = ImmutableArray.Create(
                runHelper.OriginResolveLastRev(runHelper.WorkflowOptions().ChangeBaseline));
        }

        Origin.Baseline<O>? destinationBaseline = GetDestinationBaseline(runHelper, originBaselines);

        if (destinationBaseline == null)
        {
            ValidationException.CheckCondition(
                originBaselines.Count != 0,
                "Couldn't find any parent change for %s and origin_files = %s",
                runHelper.GetResolvedRef().AsString(), runHelper.GetOriginFiles());

            throw ValidationException.RetriableException(string.Format(
                CultureInfo.InvariantCulture,
                "Couldn't find a change in the destination with {0} label that matches a change from"
                    + " the origin. Make sure to sync the submitted changes from the origin ->"
                    + " destination first or use SQUASH mode or use {1}",
                runHelper.GetOriginLabelName(),
                WorkflowOptions.ChangeRequestFromSotLimitFlag));
        }
        RunChangeRequest(runHelper, destinationBaseline, null);
    }

    private static Origin.Baseline<O>? GetDestinationBaseline<O, D>(
        WorkflowRunHelper<O, D> runHelper, IReadOnlyList<O> originRevision)
        where O : class, IRevision
        where D : class, IRevision
    {
        Origin.Baseline<O>? result = GetDestinationBaselineOneAttempt(runHelper, originRevision);
        if (result != null)
        {
            return result;
        }

        foreach (int delay in runHelper.WorkflowOptions().ChangeRequestFromSotRetry)
        {
            runHelper.GetConsole().WarnFmt(
                "Couldn't find a change in the destination with %s label and %s value."
                    + " Retrying in %s seconds...",
                runHelper.GetOriginLabelName(), originRevision, delay);
            try
            {
                Thread.Sleep(TimeSpan.FromSeconds(delay));
            }
            catch (ThreadInterruptedException e)
            {
                throw new RepoException(
                    "Interrupted while waiting for CHANGE_REQUEST_FROM_SOT destination baseline to"
                        + " be available",
                    e);
            }
            result = GetDestinationBaselineOneAttempt(runHelper, originRevision);
            if (result != null)
            {
                return result;
            }
        }
        return null;
    }

    private static Origin.Baseline<O>? GetDestinationBaselineOneAttempt<O, D>(
        WorkflowRunHelper<O, D> runHelper, IReadOnlyList<O> originRevisions)
        where O : class, IRevision
        where D : class, IRevision
    {
        var result = new Origin.Baseline<O>?[] { null };
        runHelper.GetDestinationWriter().VisitChangesWithAnyLabel(
            /* start= */ null,
            new[] { runHelper.GetOriginLabelName() },
            new ChangeRequestFromSotVisitor<O>(runHelper, originRevisions, result));
        return result[0];
    }

    private sealed class ChangeRequestFromSotVisitor<O> : IChangesLabelVisitor
        where O : class, IRevision
    {
        private readonly object _runHelper;
        private readonly IReadOnlyList<O> _originRevisions;
        private readonly Origin.Baseline<O>?[] _result;

        public ChangeRequestFromSotVisitor(
            object runHelper, IReadOnlyList<O> originRevisions, Origin.Baseline<O>?[] result)
        {
            _runHelper = runHelper;
            _originRevisions = originRevisions;
            _result = result;
        }

        public VisitResult Visit(
            Change<IRevision> change, IReadOnlyDictionary<string, string> matchedLabels)
        {
            foreach (string value in matchedLabels.Values)
            {
                foreach (O originRevision in _originRevisions)
                {
                    if (RevisionWithoutReviewInfo(originRevision.AsString())
                        .Equals(RevisionWithoutReviewInfo(value), StringComparison.Ordinal))
                    {
                        _result[0] = new Origin.Baseline<O>(
                            change.GetRevision().AsString(), originRevision);
                        return VisitResult.Terminate;
                    }
                }
            }
            return VisitResult.Continue;
        }
    }

    /// <summary>
    /// Technically revisions can contain additional metadata in the String. For example:
    /// 'aaaabbbbccccddddeeeeffff1111222233334444 PatchSet-1'. This method returns the identification
    /// part.
    /// </summary>
    private static string RevisionWithoutReviewInfo(string r) =>
        System.Text.RegularExpressions.Regex.Replace(r, " .*", "");

    private static void RunChangeRequest<O, D>(
        WorkflowRunHelper<O, D> runHelper,
        Origin.Baseline<O>? baseline,
        O? baselineForMergeImport)
        where O : class, IRevision
        where D : class, IRevision
    {
        ValidationException.CheckCondition(
            baseline != null,
            "Cannot find matching parent commit in the destination. Use '%s' flag to force a parent"
                + " commit to use as baseline in the destination.",
            WorkflowOptions.ChangeRequestParentFlag);
        // logger.atInfo().log("Found baseline %s", baseline.getBaseline());

        ChangeMigrator<O, D> migrator = runHelper.GetDefaultMigrator();
        // If --change_request_parent was used, we don't have information about the origin changes
        // included in the CHANGE_REQUEST so we assume the last change is the only change.
        IReadOnlyList<Change<O>> changes;
        if (baseline!.GetOriginRevision() == null)
        {
            changes = ImmutableArray.Create(
                runHelper.GetOriginReader().Change(runHelper.GetResolvedRef()));
        }
        else
        {
            Origin.ChangesResponse<O> changesResponse = runHelper.GetOriginReader().Changes(
                baseline.GetOriginRevision(), runHelper.GetResolvedRef());
            if (changesResponse.IsEmpty())
            {
                throw new EmptyChangeException(string.Format(
                    CultureInfo.InvariantCulture,
                    "Change '{0}' doesn't include any change for origin_files = {1}",
                    runHelper.GetResolvedRef(), runHelper.GetOriginFiles()));
            }
            changes = FilterChanges(
                changesResponse.GetChanges(), changesResponse.GetConditionalChanges(), migrator);
            if (changes.Count == 0)
            {
                string revs = changesResponse.GetChanges().Count == 0
                    ? "Unknown"
                    : string.Join(
                        ", ", changesResponse.GetChanges().Select(c => c.GetRevision().AsString()));
                migrator.FinishedMigrate(
                    ImmutableArray.Create(
                        new DestinationEffect(
                            EffectType.NOOP,
                            string.Format(
                                CultureInfo.InvariantCulture,
                                "Cannot migrate revisions [{0}]: {1}",
                                revs, "didn't affect any destination file"),
                            changesResponse.GetChanges().Cast<OriginRef>().ToList(),
                            destinationRef: null)));
                throw new EmptyChangeException(string.Format(
                    CultureInfo.InvariantCulture,
                    "Change '{0}' doesn't include any change for origin_files = {1}",
                    runHelper.GetResolvedRef(), runHelper.GetOriginFiles()));
            }
        }

        // --read-config-from-change is not implemented in CHANGE_REQUEST mode
        migrator.Migrate(
            runHelper.GetResolvedRef(),
            /*lastRev=*/ null,
            runHelper.GetConsole(),
            // Use latest change as the message/author. If it contains multiple changes the user can
            // always use metadata.squash_notes or similar.
            new Metadata(
                runHelper.GetChangeMessage(changes[^1].GetMessage()),
                runHelper.GetFinalAuthor(changes[^1].GetAuthor()),
                ImmutableListMultimap<string, string>.Empty),
            // Squash notes an Skylark API expect last commit to be the first one.
            new Changes(changes.Reverse().Cast<object>(), Array.Empty<object>()),
            baseline,
            runHelper.GetResolvedRef(),
            baselineForMergeImport);
    }

    private static void RecordNoopDestinationEffect<O, D>(
        O current, O? lastRev, WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        runHelper.GetDefaultMigrator().FinishedMigrate(
            ImmutableArray.Create(
                new DestinationEffect(
                    EffectType.NOOP,
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "No changes to migrate {0}",
                        lastRev == null
                            ? string.Format(
                                CultureInfo.InvariantCulture,
                                "up to current revision '{0}'.", current.AsString())
                            : string.Format(
                                CultureInfo.InvariantCulture,
                                "from '{0}' to current revision '{1}'",
                                lastRev.AsString(), current.AsString())),
                    /* originRefs= */ runHelper.GetChanges(lastRev, current).GetChanges()
                        .Cast<OriginRef>().ToList(),
                    /* destinationRef= */ null)));
    }

    private static void ManageNoChangesDetectedForSquash<O, D>(
        WorkflowRunHelper<O, D> runHelper, O current, O? lastRev, Origin.EmptyReason emptyReason)
        where O : class, IRevision
        where D : class, IRevision
    {
        switch (emptyReason)
        {
            case Origin.EmptyReason.NoChanges:
            {
                string noChangesMsg = string.Format(
                    CultureInfo.InvariantCulture,
                    "No changes{0} up to {1} match any origin_files",
                    lastRev == null ? "" : " from " + lastRev.AsString(), current.AsString());
                if (!runHelper.IsForce())
                {
                    RecordNoopDestinationEffect(current, lastRev, runHelper);
                    throw new EmptyChangeException(string.Format(
                        CultureInfo.InvariantCulture,
                        "{0}. Use {1} if you really want to run the migration anyway (For example if"
                            + " the copy.bara.sky file has changed).",
                        noChangesMsg, GeneralOptions.Force));
                }
                runHelper.GetConsole().WarnFmt(
                    "%s. Migrating anyway because of %s", noChangesMsg, GeneralOptions.Force);
                break;
            }
            case Origin.EmptyReason.ToIsAncestor:
            {
                if (!runHelper.IsForce())
                {
                    throw new EmptyChangeException(string.Format(
                        CultureInfo.InvariantCulture,
                        "'{0}' has been already migrated. Use {1} if you really want to run the"
                            + " migration again (For example if the copy.bara.sky file has changed).",
                        current.AsString(), GeneralOptions.Force));
                }
                runHelper.GetConsole().WarnFmt(
                    "'%s' has been already migrated. Migrating anyway because of %s",
                    lastRev!.AsString(), GeneralOptions.Force);
                break;
            }
            case Origin.EmptyReason.UnrelatedRevisions:
            {
                ValidationException.CheckCondition(
                    runHelper.IsForce(),
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "Last imported revision '{0}' is not an ancestor of the revision currently"
                            + " being migrated ('{1}'). Use {2} if you really want to migrate the"
                            + " reference.",
                        lastRev!, current.AsString(), GeneralOptions.Force));
                runHelper.GetConsole().WarnFmt(
                    "Last imported revision '%s' is not an ancestor of the revision currently being"
                        + " migrated ('%s')",
                    lastRev, current.AsString());
                break;
            }
        }
    }

    public static bool IsHistorySupported<O, D>(WorkflowRunHelper<O, D> helper)
        where O : class, IRevision
        where D : class, IRevision =>
        helper.DestinationSupportsPreviousRef() && helper.GetOriginReader().SupportsHistory();

    internal static IReadOnlyList<Change<O>> FilterChanges<O, D>(
        IReadOnlyList<Change<O>> detectedChanges,
        IReadOnlyDictionary<Change<O>, Change<O>> conditionalChanges,
        ChangeMigrator<O, D> changeMigrator)
        where O : class, IRevision
        where D : class, IRevision
    {
        var includedChanges = detectedChanges
            .Where(e => !changeMigrator.SkipChange(e))
            .ToList();

        // For all the changes that should be included based on skipChange, find the ones that should
        // be added unconditionally.
        var unconditionalChanges = includedChanges
            .Where(e => !conditionalChanges.ContainsKey(e))
            .ToImmutableHashSet();

        // Only include unconditional changes or conditional changes whose dependant change is
        // included.
        return includedChanges
            .Where(e => unconditionalChanges.Contains(e)
                || (conditionalChanges.TryGetValue(e, out var dep) && unconditionalChanges.Contains(dep)))
            .ToImmutableArray();
    }

    /// <summary>Returns the last rev if possible. If --force is not enabled it will fail if not found.</summary>
    public static O? MaybeGetLastRev<O, D>(WorkflowRunHelper<O, D> runHelper)
        where O : class, IRevision
        where D : class, IRevision
    {
        try
        {
            return runHelper.GetLastRev();
        }
        catch (CannotResolveRevisionException e)
        {
            if (runHelper.IsForce())
            {
                runHelper.GetConsole().WarnFmt(
                    "Cannot find last imported revision, but proceeding because of %s flag",
                    GeneralOptions.Force);
            }
            else
            {
                throw new ValidationException(
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "Cannot find last imported revision. Use {0} if you really want to proceed"
                            + " with the migration use, or use '--last-rev' to override the revision.",
                        GeneralOptions.Force),
                    e);
            }
            return null;
        }
    }
}
