# Copyright 2016 Google Inc. All Rights Reserved.

licenses(["unencumbered"])  # Owned by Google. No external contributions

# Disabled for now. Doesn't compile. It is surprisingly difficult to make
# tools.jar available...
#
# java_test(
#   name = "MarkdownGeneratorTest",
#   srcs = ["MarkdownGeneratorTest.java",],
#   test_class = "com.google.copybara.doc.MarkdownGeneratorTest",
#   deps = [
#      "//java/com/google/copybara:copybara_lib",
#      "//java/com/google/copybara/doc:annotations",
#      "//third_party:autocommon",
#      "//third_party:guava",
#      "//third_party:jcommander",
#      "//third_party:junit4",
#      "//third_party:truth",
#   ],
#   data = [
#      "@bazel_tools//third_party/java/jdk/langtools:javac_jar",
#   ],
#   jvm_flags = [
#      # Simulates how Bazel invokes JavaBuilder
#      "-Xbootclasspath/p:$(location @bazel_tools//third_party/java/jdk/langtools:javac_jar)",
#   ],
# )

