name: Build and Publish Copybara

on:
  push:
    branches:
      - "master"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Install Bazelisk
      #  run: |
      #    curl -sLo bazelisk https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
      #    chmod +x bazelisk
      #    sudo mv bazelisk /usr/local/bin/bazelisk

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Copybara
        run: |
          bazelisk build --java_language_version=11 --tool_java_language_version=11 --java_runtime_version=remotejdk_11 //java/com/google/copybara:copybara_deploy.jar

      - name: Rename JAR file
        run: |
          mv bazel-bin/java/com/google/copybara/copybara_deploy.jar copybara.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            copybara.jar
